# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
gomod:
  proxy: true
builds:
  - goarch:
      - amd64
      - arm64
    goos: [linux]
    env:
      - CGO_ENABLED=0
nfpms:
  - vendor: Becker Software LTDA
    homepage: https://carlosbecker.com
    maintainer: Carlos Becker <root@carlosbecker.dev>
    description: Exports Solarman metrics in the Prometheus format
    formats:
      - deb
      - apk
      - rpm
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Arch }}"
